name    'dustinrc-virtualenv'
version '0.1.0'
source 'git://github.com/dustinrc/puppet-virtualenv.git'
author 'Dustin Chapman'
license 'Apache License, Version 2.0'
summary 'virtualenv Module'
description 'virtualenv Module for Arch, CentOS, Debian, Fedora, Gentoo, RHEL, Ubuntu.'
project_page 'https://github.com/dustinrc/puppet-virtualenv'
